import type { Metadata } from 'next'
import { MuseoModerno,Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar/navbar'

const muse = Inter({
  weight: '400',
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props:any){
  return (
    <html lang="en">
      <body className={muse.className}>
      <div className='bg-[#ECF0F3] w-full  h-full'>
          <div className='z-0'>
            <Navbar />
          </div>
          <div className='flex pb-24 z-0'>
            <div className=''> {props.children} </div>
          </div>
      </div>
        </body>
    </html>
  )
}
